version: 2

sources:
##TODO: either remove or configure add create this source in other warehouses beside athena
  - name: guy_playground
    database: guyA
    schema: guy_playground2
    tables:
      - name: players
        description: This table has basic information about football players
        columns:
          - name: age
          - name: first_name
          - name: last_name
          - name: team
          - name: shirt_number
  - name: dremio-s3
    database: ElementaryS3
    schema: dremio-playground.guy-cloud.guyuppercase
    tables:
      - name: orders_validation_v2
  - name: athena
    database: ElementaryGlue
    schema: guy_playground
    tables:
      - name: orders_v2_athena
        columns:
          - name: id
          - name: order_date
          - name: user_id
          - name: status
  - name: athena_elementary
    database: ElementaryGlue
    schema: guy_playground_elementary
    tables:
      - name: dbt_run_results
        columns:
          - name: model_execution_id
            data_type: string
            description: Execution id generated by joining the unique_id of the resource and the invocation_id. This is the unique key of each row in this model.

          - name: unique_id
            data_type: string
            description: The unique id of the resource (would be similar for all executions of the same resource).

          - name: invocation_id
            data_type: string
            description: The unique id of the invocation (would be similar for all resources executed on the same invocation). FK to dbt_invocations.

          - name: generated_at
            data_type: string
            description: ""

          - name: name
            data_type: string
            description: Resource name.

          - name: message
            data_type: string
            description: Execution results message returned by dbt.

          - name: status
            data_type: string
            description: Execution result status (success, error, pass, fail)

          - name: resource_type
            data_type: string
            description: Resource type (model, test, snapshot, seed, etc)

          - name: execution_time
            data_type: float
            description: Resource execution duration in seconds.

          - name: execute_started_at
            data_type: string
            description: Start time of the execution.

          - name: execute_completed_at
            data_type: string
            description: End time of the execution.

          - name: compile_started_at
            data_type: string
            description: Start time of resource compile action.

          - name: compile_completed_at
            data_type: string
            description: End time of resource compile action.

          - name: rows_affected
            data_type: int
            description: ""

          - name: full_refresh
            data_type: boolean
            description: Was this a full refresh execution.

          - name: compiled_code
            data_type: string
            description: The compiled code (SQL / Python) executed against the database.

          - name: failures
            data_type: int
            description: Number of failures in this run.

          - name: query_id
            data_type: string
            description: Query ID in the data warehouse, if returned by the adapter (currently only supported in Snowflake, is null for any other adapter).

          - name: thread_id
            data_type: string
            description: Id of the thread of this resource run.

          - name: adapter_response
            data_type: string
            description: Response returned by the adapter (Fields will be different for each adapters).
      - name: dbt_invocations
        columns:
          - name: invocation_id
            data_type: string
            description: Primary key of this table.

          - name: run_started_at
            data_type: string
            description: Timestamp the invocation was started.

          - name: run_completed_at
            data_type: string
            description: Timestamp the invocation was completed

          - name: generated_at
            data_type: string
            description: The time this invocation was uploaded to the database.

          - name: command
            data_type: string
            description: dbt command that was used. For example, run.

          - name: dbt_version
            data_type: string
            description: Version of dbt that was used in this invocation.

          - name: elementary_version
            data_type: string
            description: Version of the elementary package that was used in this invocation.

          - name: full_refresh
            data_type: boolean
            description: Whether or not this invocation was executed as a full-refresh.

          - name: invocation_vars
            data_type: string
            description: Dictionary of the variables (and values) that were declared in the invocation.

          - name: vars
            data_type: string
            description: Dictionary of all variables (and values) in the dbt project. If none were declared at runtime, these are the variables declared in dbt_project yml

          - name: target_name
            data_type: string
            description: Name of the target used in this invocation.

          - name: target_database
            data_type: string
            description: Name of the target database that was used in this invocation.

          - name: target_schema
            data_type: string
            description: Name of the target schema that was used in this invocation.

          - name: target_profile_name
            data_type: string
            description: Name of the dbt profile that was used in this invocation.

          - name: threads
            data_type: integer
            description: Number of threads that were used to run this dbt invocation. (This number could impact the performance of a dbt invocation).

          - name: selected
            data_type: string
            description: The selected resources in the dbt command. While this is a string in the database, this can easily be converted to an array.

          - name: yaml_selector
            data_type: string
            description: The yaml selector that was passed in this invocation.

          - name: job_id
            data_type: string
            description: The ID of a job, defined in the `job_id` var or in the `JOB_ID` env var or by the orchestrator (dbt Cloud, GitHub Actions, etc).

          - name: job_name
            data_type: string
            description: The name of a job, defined in the `job_name` var or in the `JOB_NAME` env var.

          - name: job_run_id
            data_type: string
            description: The run ID of a job, defined in the `job_run_id` var or in the `DBT_JOB_RUN_ID` env var or by the orchestrator (dbt Cloud, GitHub Actions, etc).

          - name: env
            data_type: string
            description: The environment's name, defined in the `DBT_ENV` env var.

          - name: env_id
            data_type: string
            description: The ID of an environment, defined in the `DBT_ENV_ID` env var.

          - name: project_id
            data_type: string
            description: The ID of a project, defined in the `DBT_PROJECT_ID` env var or by the orchestrator (dbt Cloud, GitHub Actions, etc).

          - name: cause_category
            data_type: string
            description: |
              The category of the cause of the invocation. For example, if the invocation was triggered by a schedule, the cause category would be schedule.
              Defined in the `DBT_CAUSE_CATEGORY` env var or by the orchestrator (dbt Cloud, GitHub Actions, etc).

          - name: cause
            data_type: string
            description: |
              The cause of the invocation. For example, if the invocation was triggered by a manual run, the cause would be _"Kicked off by Joe."_.
              Defined in the `DBT_CAUSE` env var or by the orchestrator (dbt Cloud, GitHub Actions, etc).

          - name: pull_request_id
            data_type: string
            description: The ID of a pull request, defined in the `DBT_PULL_REQUEST_ID` env var or by the orchestrator (dbt Cloud, GitHub Actions, etc).

          - name: git_sha
            data_type: string
            description: The git SHA of the commit that was used in this invocation, defined in the `DBT_GIT_SHA` env var or by the orchestrator (dbt Cloud, GitHub Actions, etc).

          - name: orchestrator
            data_type: string
            description: The orchestrator that was used to run this invocation, defined in the `orchestrator` var or in the `ORCHESTRATOR` env var or by the orchestrator env vars. For example, dbt Cloud, GitHub Actions, etc.

          - name: job_url
            data_type: string
            description: The name of a job, defined in the `job_url` var or in the `JOB_URL` env var or by the orchestrator. For GitHub Actions orchestrator, the value is calculated.

          - name: account_id
            data_type: string
            description: The ID of the account, defined in the `account_id` var or in the `ACCOUNT_ID` env var or by the orchestrator.
models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders
    config:
      tags: ["PII"]
      elementary:
        timestamp_column: "signup_date"
    tests:
      - elementary.volume_anomalies:
          name: customer_volume_anomalies_custom_name
          alias: customer_volume_anomalies_alias_name
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed
        tests:
          - elementary.column_anomalies:
              config:
                severity: warn
              tags: ["column_anomalies"]
              arguments:
                column_anomalies:
                  - zero_count
                timestamp_column: "signup_date"

      - name: customer_lifetime_value
        description: Total value (AUD) of a customer's orders

      - name: customer_email
        description: Customer's email. PII.

      - name: signup_date
        description: Date (UTC) of a customer's signup to the online shop.

  - name: orders
    description: This table has basic information about orders, as well as some derived facts based on payments
    config:
      tags: ["finance"]
      elementary:
        timestamp_column: "order_date"

    tests:
      - elementary.dimension_anomalies:
          arguments:
            dimensions:
              - status
    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: returned_orders
    description: This table contains all of the returned orders
    config:
      tags: ["finance"]

    tests:
      - elementary.volume_anomalies:
          tags: ["table_anomalies"]
          arguments:
            timestamp_column: "order_date"
      - elementary.collect_metrics:
          arguments:
            timestamp_column: "order_date"
          metrics:
            - name: average_amount
              type: average
              columns: [amount]
          days_back: 365

    columns:
      - name: order_id
        description: This is a unique identifier for an order

      - name: customer_id
        description: Foreign key to the customers table

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'

      - name: amount
        description: Total amount (AUD) of the order

      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card

      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon

      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer

      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card

  - name: family_stats
    description: This table contains statistics about a family
    config:
      tags: ["family"]
    columns:
      - name: last_name
        description: The last name of the family
      - name: member_count
        description: The number of members in the family
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                max_value: 3
                inclusive: true
      - name: oldest_member
        description: The age of the oldest member of the family

      - name: youngest_member
        description: The age of the youngest member of the family

      - name: female_count
        description: The number of females in the family

      - name: male_count
        description: The number of males in the family

  - name: teams
    description: This table contains statistics about a football team
    columns:
      - name: team
        description: The name of the team
      - name: player_count
        description: The number of players in the team
      - name: oldest_player
        description: The age of the oldest player in the team
      - name: youngest_player
        description: The age of the youngest player in the team
      - name: average_age
        description: The average age of the players in the team
      - name: ten_shirt_worn
        description: Whether the team wears the number 10 shirt

  - name: athena_dremio_comparison
    description: This table contains the comparison between athena and glue
    columns:
      - name: unique_id
        description: The unique id of the resource
      - name: athena_invocation_id
        description: The invocation id of the resource in athena
      - name: dremio_invocation_id
        description: The invocation id of the resource in dremio
      - name: athena_status
        description: The status of the resource in athena
      - name: dremio_status
        description: The status of the resource in dremio
      - name: athena_execution_time
        description: The execution time of the resource in athena
      - name: dremio_execution_time
        description: The execution time of the resource in dremio
      - name: faster_warehouse
        description: The faster warehouse between athena and dremio